// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA532-eIG1geQsl7kINzrL_ZUkxuaZC1KE',
    appId: '1:260675355930:web:91b5d29e50ca3f878898a3',
    messagingSenderId: '260675355930',
    projectId: 'testrafahiaapp',
    authDomain: 'testrafahiaapp.firebaseapp.com',
    storageBucket: 'testrafahiaapp.appspot.com',
    measurementId: 'G-VW942HFNP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaGB7KNcwXV2F1G4uWJ3YsueN7MdfPDdo',
    appId: '1:260675355930:android:ad33802755a735028898a3',
    messagingSenderId: '260675355930',
    projectId: 'testrafahiaapp',
    storageBucket: 'testrafahiaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZMAb2eMlVnOCrIdm3dqcJVuwHCPwcVwM',
    appId: '1:260675355930:ios:40e87775c43934ba8898a3',
    messagingSenderId: '260675355930',
    projectId: 'testrafahiaapp',
    storageBucket: 'testrafahiaapp.appspot.com',
    iosBundleId: 'com.example.rafahiaAppFinalEmy',
  );
}
